version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
       - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: banco-beer-database
    ports:
      - "6033:3306"

volumes:
  database: